steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"]
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=gke.yaml
      - --image=gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA
      - --location=us-central1-c
      - --cluster=cluster-1
      - --namespace=flask-app-prod

substitutions:
  _PROJECT_ID: $PROJECT_ID
  _REPO_NAME: $REPO_NAME
  _COMMIT_SHA: $COMMIT_SHA
