steps:
  - name: "build docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA", "."]
  - name: "push docker"
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"]
  - name: "deploy to gke"
    args:
      - run
      - --filename=gke.yaml
      - --image=gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA
      - --locatuiotn=us-central1-c
      - --cluster=cluster-1
      - --namespace=flask-app-prod
