apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app-container
          image: gcr.io/clean-wonder-400608/sample-docker-flask-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
